// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.17.1
// source: packet.proto

package fighter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketID_T int32

const (
	PacketID_NONE             PacketID_T = 0
	PacketID_SC_CONNECT       PacketID_T = 1
	PacketID_CS_CONNECT       PacketID_T = 2
	PacketID_SC_CHAT_USER_MSG PacketID_T = 3
	PacketID_CS_CHAT_USER_MSG PacketID_T = 4
	PacketID_SC_PING          PacketID_T = 5
	PacketID_CS_PONG          PacketID_T = 6
	PacketID_SC_ROOM_CREATE   PacketID_T = 7
	PacketID_CS_ROOM_CREATE   PacketID_T = 8
	PacketID_SC_ROOM_ENTER    PacketID_T = 9
	PacketID_CS_ROOM_ENTER    PacketID_T = 10
	PacketID_SC_ECHO          PacketID_T = 1000
	PacketID_CS_ECHO          PacketID_T = 1001
)

// Enum value maps for PacketID_T.
var (
	PacketID_T_name = map[int32]string{
		0:    "NONE",
		1:    "SC_CONNECT",
		2:    "CS_CONNECT",
		3:    "SC_CHAT_USER_MSG",
		4:    "CS_CHAT_USER_MSG",
		5:    "SC_PING",
		6:    "CS_PONG",
		7:    "SC_ROOM_CREATE",
		8:    "CS_ROOM_CREATE",
		9:    "SC_ROOM_ENTER",
		10:   "CS_ROOM_ENTER",
		1000: "SC_ECHO",
		1001: "CS_ECHO",
	}
	PacketID_T_value = map[string]int32{
		"NONE":             0,
		"SC_CONNECT":       1,
		"CS_CONNECT":       2,
		"SC_CHAT_USER_MSG": 3,
		"CS_CHAT_USER_MSG": 4,
		"SC_PING":          5,
		"CS_PONG":          6,
		"SC_ROOM_CREATE":   7,
		"CS_ROOM_CREATE":   8,
		"SC_ROOM_ENTER":    9,
		"CS_ROOM_ENTER":    10,
		"SC_ECHO":          1000,
		"CS_ECHO":          1001,
	}
)

func (x PacketID_T) Enum() *PacketID_T {
	p := new(PacketID_T)
	*p = x
	return p
}

func (x PacketID_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketID_T) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_proto_enumTypes[0].Descriptor()
}

func (PacketID_T) Type() protoreflect.EnumType {
	return &file_packet_proto_enumTypes[0]
}

func (x PacketID_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketID_T.Descriptor instead.
func (PacketID_T) EnumDescriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0, 0}
}

type MoveDir_T int32

const (
	MoveDir_LL MoveDir_T = 0
	MoveDir_LU MoveDir_T = 1
	MoveDir_UU MoveDir_T = 2
	MoveDir_RU MoveDir_T = 3
	MoveDir_RR MoveDir_T = 4
	MoveDir_RD MoveDir_T = 5
	MoveDir_DD MoveDir_T = 6
	MoveDir_LD MoveDir_T = 7
)

// Enum value maps for MoveDir_T.
var (
	MoveDir_T_name = map[int32]string{
		0: "LL",
		1: "LU",
		2: "UU",
		3: "RU",
		4: "RR",
		5: "RD",
		6: "DD",
		7: "LD",
	}
	MoveDir_T_value = map[string]int32{
		"LL": 0,
		"LU": 1,
		"UU": 2,
		"RU": 3,
		"RR": 4,
		"RD": 5,
		"DD": 6,
		"LD": 7,
	}
)

func (x MoveDir_T) Enum() *MoveDir_T {
	p := new(MoveDir_T)
	*p = x
	return p
}

func (x MoveDir_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveDir_T) Descriptor() protoreflect.EnumDescriptor {
	return file_packet_proto_enumTypes[1].Descriptor()
}

func (MoveDir_T) Type() protoreflect.EnumType {
	return &file_packet_proto_enumTypes[1]
}

func (x MoveDir_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveDir_T.Descriptor instead.
func (MoveDir_T) EnumDescriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{1, 0}
}

type PacketID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PacketID) Reset() {
	*x = PacketID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketID) ProtoMessage() {}

func (x *PacketID) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketID.ProtoReflect.Descriptor instead.
func (*PacketID) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

type MoveDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveDir) Reset() {
	*x = MoveDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDir) ProtoMessage() {}

func (x *MoveDir) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDir.ProtoReflect.Descriptor instead.
func (*MoveDir) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{1}
}

var File_packet_proto protoreflect.FileDescriptor

var file_packet_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x66, 0x69, 0x67, 0x68, 0x74, 0x65, 0x72, 0x22, 0xea, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x44, 0x22, 0xdd, 0x01, 0x0a, 0x01, 0x54, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x43, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x53,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x04,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x43, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x53, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43,
	0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x07, 0x12, 0x12,
	0x0a, 0x0e, 0x43, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x43, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x5f, 0x45, 0x4e,
	0x54, 0x45, 0x52, 0x10, 0x09, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x53, 0x5f, 0x52, 0x4f, 0x4f, 0x4d,
	0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x0a, 0x12, 0x0c, 0x0a, 0x07, 0x53, 0x43, 0x5f, 0x45,
	0x43, 0x48, 0x4f, 0x10, 0xe8, 0x07, 0x12, 0x0c, 0x0a, 0x07, 0x43, 0x53, 0x5f, 0x45, 0x43, 0x48,
	0x4f, 0x10, 0xe9, 0x07, 0x22, 0x4e, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x22,
	0x43, 0x0a, 0x01, 0x54, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x4c, 0x55, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x55, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02,
	0x52, 0x55, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x52, 0x52, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02,
	0x52, 0x44, 0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x44, 0x10, 0x06, 0x12, 0x06, 0x0a, 0x02,
	0x4c, 0x44, 0x10, 0x07, 0x42, 0x0d, 0x50, 0x01, 0x5a, 0x09, 0x2e, 0x2f, 0x66, 0x69, 0x67, 0x68,
	0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData = file_packet_proto_rawDesc
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(file_packet_proto_rawDescData)
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packet_proto_goTypes = []interface{}{
	(PacketID_T)(0),  // 0: fighter.PacketID.T
	(MoveDir_T)(0),   // 1: fighter.MoveDir.T
	(*PacketID)(nil), // 2: fighter.PacketID
	(*MoveDir)(nil),  // 3: fighter.MoveDir
}
var file_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packet_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		EnumInfos:         file_packet_proto_enumTypes,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_rawDesc = nil
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
